steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME:$_TAG', '.']

  # 2. Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME:$_TAG']

# These are the variables passed from GitHub Actions
substitutions:
  _TAG: 'latest'
  _IMAGE_NAME: 'gcr.io/my-project/my-app' # default fallback